#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,                    sensorI2CMuxController)
#pragma config(Sensor, S4,     HTPB,                sensorI2CCustom9V)
#pragma config(Motor,  motorA,          ,              tmotorNormal, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorNormal, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "common.h"
#include "HTAC-driver.h"
#include "HTMAG-driver.h"
#include "HTMC-driver.h"
#include "LEGOLS-driver.h"
#include "LEGOTS-driver.h"
#include "HTPB-driver.h"
#include "HTIRS2-driver.h"
#include "HTGYRO-driver.h"
#include "JoystickDriver.c"

int threshold = 20;

task magnetSensor()
{

  long inputdata = 2;

  if (HTPBsetupIO(HTPB, 0x02))
     //writeDebugStreamLine("SetupWorked");
  HTPBwriteIO(HTPB,0x00);

  while(true) {

    // Read sensor from port b5
    inputdata = HTPBreadIO(HTPB, 0x20);// 0x20 is the mask for port b5


    writeDebugStreamLine("Input Data is: %d", inputdata);

    if (inputdata)
    {
      HTPBwriteIO(HTPB,0x02);
      servo[servo2] = 0;
    }
    else
    {
      HTPBwriteIO(HTPB,0);

      servo[servo2] = 125;
    }

     wait1Msec(100);
  }
}

void initialize()
{
  servo[servo1] = 250;
  servo[servo2] = 10;
  servo[servo3] = 250;
  servo[servo4] = 139;
  servo[servo5] = 75;
}

task main()
{
  servoChangeRate[servo2] = 5;
  initialize();
  StartTask(magnetSensor);

  while(true)
  {
    getJoystickSettings(joystick);

    //Driving Motor 1

    if(abs(joystick.joy1_y1) > threshold)
    {
      motor[motorF] = joystick.joy1_y1;
    }
    else
    {
      motor[motorF] = 0;
    }

    //Driving Motor 2

    if(abs(joystick.joy1_y2) > threshold)
    {
      motor[motorG] = joystick.joy1_y2;
    }
    else
    {
      motor[motorG] = 0;
    }

    //Movement Treads 1

    if(abs(joystick.joy2_y1) > threshold)
    {
      motor[motorD] = joystick.joy2_y1;
    }
    else
    {
      motor[motorD] = 0;
    }

    //Movement Treads 2

    if(abs(joystick.joy2_y2) > threshold)
    {
      motor[motorE] = joystick.joy2_y2;
    }
    else
    {
      motor[motorE] = 0;
    }

    if(joy2Btn(1))
    {
      servo[servo1] = 150;
    }

    else
    {
      servo[servo1] = 250;
    }

    if(joy2Btn(2))
    {
      servo[servo3] = 150;
    }

    else
    {
      servo[servo3] = 250;
    }

    if(joy2Btn(4))
    {
     servo[servo4] = 20;
       //servo[servo4] = 0;
      wait1Msec(350);
      servo[servo5] = 255;
     // servo[servo5] = 100;
    }

    if(joy2Btn(3))
    {
      servo[servo5] = 75;
      wait1Msec(350);
      servo[servo4] = 139;
    }

    if(joy2Btn(6)) //nxt motors
    {
      motor[motorA] = 100;   // Motor C is run at a power level of 100.
      motor[motorB] = 100;
    }
    else
      motor[motorA] = 0;   // Motor C is run at a power level of 100.
      motor[motorB] = 0;

  }
}
